import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Intro from '../components/Intro'
import Contact from '../components/Contact'
import Services from '../components/Services'
import Technology from '../components/Technology'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
     <Intro/>
     <Services/>
     <Technology/>
     <Contact/>
   
     <Footer/>
      
    </div>
  )
}
